apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localstack7-ingress
  namespace: mission7
spec:
  ingressClassName: nginx
  rules:
    - host: midominio.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: localstack7
                port:
                  number: 4566